# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/../har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from testcases.login_test import TestCaseMubuLogin as MuBuLogin

import pytest
from httprunner import Parameters

class TestCaseCreateFolder(HttpRunner):
    @pytest.mark.parametrize(
        'params',Parameters({
                'folderTitle':['title-1','title-2','title-3']
            }
        )
    )
    def test_start(self, params):
        super().test_start(params)

    config = (
        Config("testcase description")
            .variables(**{
            'host': 'https://mubu.com',
            'phone': '13777866085',
            'password': 'jinjiamin'
        })
            .base_url('${host}')
            .export('data_unique_id','JwtToken','user_persistence')
            .verify(False)
    )

    teststeps = [
        Step(
            RunTestCase('login')
            .call(MuBuLogin)
            .export('data_unique_id', 'JwtToken', 'user_persistence')
        ),
        Step(
            RunRequest("/list")
            .get("/list")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "referer": "${host}/login/password",
                    "upgrade-insecure-requests": "1",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    #"reg_entrance": "https%3A%2F%2Fmubu.com%2Flogin",
                    #"_ga": "GA1.2.393581119.1603338104",
                    #"_gid": "GA1.2.1468470317.1603338104",
                    "SLARDAR_WEB_ID": "7a0c881a-6a71-470c-8a30-dea50daba2ba",
                    #"Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1603338106",
                    #"Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1603374277",
                    "reg_focusId": "76176d95-2ea5-4aec-9761-175508ddf8e",
                    "reg_prepareId": "175508dda07-175508dd9c7-4aec-9761-7187bf8b79ba",
                    "mubu_inner": "1",
                    "s_v_web_id": "kgka62xo_moCbdJQ2_5Fuf_4EBO_8WEd_8JqwkBNYPNKm",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "55729c10-146c-11eb-88df-75fccb220896",
                    #"csrf_token": "a170eeb3-dcb8-4801-8a35-4227ae1c8392",
                    "SESSION": "40d77cbd-f81c-4c8f-b018-85c4c3e6e94b",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("/api/list/tip_new_update")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "${host}",
                    "referer": "${host}/list",
                    "content-length": "0",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    #"reg_entrance": "https%3A%2F%2Fmubu.com%2Flogin",
                    #"_ga": "GA1.2.393581119.1603338104",
                    #"_gid": "GA1.2.1468470317.1603338104",
                    "SLARDAR_WEB_ID": "7a0c881a-6a71-470c-8a30-dea50daba2ba",
                    #"Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1603338106",
                    #"Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1603374277",
                    "reg_focusId": "76176d95-2ea5-4aec-9761-175508ddf8e",
                    "reg_prepareId": "175508dda07-175508dd9c7-4aec-9761-7187bf8b79ba",
                    "mubu_inner": "1",
                    "s_v_web_id": "kgka62xo_moCbdJQ2_5Fuf_4EBO_8WEd_8JqwkBNYPNKm",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "55729c10-146c-11eb-88df-75fccb220896",
                    #"csrf_token": "a170eeb3-dcb8-4801-8a35-4227ae1c8392",
                    "SESSION": "40d77cbd-f81c-4c8f-b018-85c4c3e6e94b",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "x-requested-with": "XMLHttpRequest",
                    "content-length": "38",
                    "origin": "${host}",
                    "referer": "${host}/list",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    #"reg_entrance": "https%3A%2F%2Fmubu.com%2Flogin",
                    #"_ga": "GA1.2.393581119.1603338104",
                    #"_gid": "GA1.2.1468470317.1603338104",
                    "SLARDAR_WEB_ID": "7a0c881a-6a71-470c-8a30-dea50daba2ba",
                    #"Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1603338106",
                    #"Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1603374277",
                    "reg_focusId": "76176d95-2ea5-4aec-9761-175508ddf8e",
                    "reg_prepareId": "175508dda07-175508dd9c7-4aec-9761-7187bf8b79ba",
                    "mubu_inner": "1",
                    "s_v_web_id": "kgka62xo_moCbdJQ2_5Fuf_4EBO_8WEd_8JqwkBNYPNKm",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "55729c10-146c-11eb-88df-75fccb220896",
                    #"csrf_token": "a170eeb3-dcb8-4801-8a35-4227ae1c8392",
                    "SESSION": "40d77cbd-f81c-4c8f-b018-85c4c3e6e94b",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                }
            )
            .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("/api/message/get_message_unread")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "${host}",
                    "referer": "${host}/list",
                    "content-length": "0",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    #"reg_entrance": "https%3A%2F%2Fmubu.com%2Flogin",
                    #"_ga": "GA1.2.393581119.1603338104",
                    #"_gid": "GA1.2.1468470317.1603338104",
                    "SLARDAR_WEB_ID": "7a0c881a-6a71-470c-8a30-dea50daba2ba",
                    #"Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1603338106",
                    #"Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1603374277",
                    "reg_focusId": "76176d95-2ea5-4aec-9761-175508ddf8e",
                    "reg_prepareId": "175508dda07-175508dd9c7-4aec-9761-7187bf8b79ba",
                    "mubu_inner": "1",
                    "s_v_web_id": "kgka62xo_moCbdJQ2_5Fuf_4EBO_8WEd_8JqwkBNYPNKm",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "55729c10-146c-11eb-88df-75fccb220896",
                    #"csrf_token": "a170eeb3-dcb8-4801-8a35-4227ae1c8392",
                    "SESSION": "40d77cbd-f81c-4c8f-b018-85c4c3e6e94b",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                }
            )
            .with_data("")
            .teardown_hook('${get_unreadCount($response)}','unreadCount')
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal('$unreadCount',0)
        ),
        Step(
            RunRequest("/api/list/create_folder")
            .post("/api/list/create_folder")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "x-requested-with": "XMLHttpRequest",
                    "content-length": "20",
                    "origin": "${host}",
                    "referer": "${host}/list",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    #"reg_entrance": "https%3A%2F%2Fmubu.com%2Flogin",
                    #"_ga": "GA1.2.393581119.1603338104",
                    #"_gid": "GA1.2.1468470317.1603338104",
                    "SLARDAR_WEB_ID": "6e65fccd-5ed3-470b-af39-740f1197e27d",
                    #"Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1603338106",
                    #"Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1603374278",
                    "reg_focusId": "76176d95-2ea5-4aec-9761-175508ddf8e",
                    "reg_prepareId": "175508dda07-175508dd9c7-4aec-9761-7187bf8b79ba",
                    "mubu_inner": "1",
                    "s_v_web_id": "kgka62xo_moCbdJQ2_5Fuf_4EBO_8WEd_8JqwkBNYPNKm",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "55729c10-146c-11eb-88df-75fccb220896",
                    #"csrf_token": "a170eeb3-dcb8-4801-8a35-4227ae1c8392",
                    "SESSION": "40d77cbd-f81c-4c8f-b018-85c4c3e6e94b",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                }
            )
            .with_data({"folderId": "0", "name": "${get_random_title()}"})
            .extract()
            .with_jmespath('body.data.folder.id','folder_id')
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "x-requested-with": "XMLHttpRequest",
                    "content-length": "38",
                    "origin": "${host}",
                    "referer": "${host}/list",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    #"reg_entrance": "https%3A%2F%2Fmubu.com%2Flogin",
                    #"_ga": "GA1.2.393581119.1603338104",
                    #"_gid": "GA1.2.1468470317.1603338104",
                    "SLARDAR_WEB_ID": "6e65fccd-5ed3-470b-af39-740f1197e27d",
                    #"Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1603338106",
                    #"Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1603374278",
                    "reg_focusId": "76176d95-2ea5-4aec-9761-175508ddf8e",
                    "reg_prepareId": "175508dda07-175508dd9c7-4aec-9761-7187bf8b79ba",
                    "mubu_inner": "1",
                    "s_v_web_id": "kgka62xo_moCbdJQ2_5Fuf_4EBO_8WEd_8JqwkBNYPNKm",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "55729c10-146c-11eb-88df-75fccb220896",
                    #"csrf_token": "a170eeb3-dcb8-4801-8a35-4227ae1c8392",
                    "SESSION": "40d77cbd-f81c-4c8f-b018-85c4c3e6e94b",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                }
            )
            .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/rename_folder")
            .post("/api/list/rename_folder")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "accept-encoding": "gzip, deflate, br",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "x-requested-with": "XMLHttpRequest",
                    "content-length": "32",
                    "origin": "${host}",
                    "referer": "${host}/list",
                    "te": "trailers",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    #"reg_entrance": "https%3A%2F%2Fmubu.com%2Flogin",
                    #"_ga": "GA1.2.393581119.1603338104",
                    #"_gid": "GA1.2.1468470317.1603338104",
                    "SLARDAR_WEB_ID": "6e65fccd-5ed3-470b-af39-740f1197e27d",
                    #"Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1603338106",
                    #"Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1603374278",
                    "reg_focusId": "76176d95-2ea5-4aec-9761-175508ddf8e",
                    "reg_prepareId": "175508dda07-175508dd9c7-4aec-9761-7187bf8b79ba",
                    "mubu_inner": "1",
                    "s_v_web_id": "kgka62xo_moCbdJQ2_5Fuf_4EBO_8WEd_8JqwkBNYPNKm",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "55729c10-146c-11eb-88df-75fccb220896",
                    #"csrf_token": "a170eeb3-dcb8-4801-8a35-4227ae1c8392",
                    "SESSION": "40d77cbd-f81c-4c8f-b018-85c4c3e6e94b",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                }
            )
            .with_data({"folderId": "${folder_id}", "name": "${folderTitle}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateFolder().test_start()
